//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.tblSysRoles = new HashSet<tblSysRole>();
        }
    
        public int DeptID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public string OrgID { get; set; }
        public string BranchID { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDatetTime { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysRole> tblSysRoles { get; set; }
    }
}
