//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessType()
        {
            this.BusinessTypeMarginDetails = new HashSet<BusinessTypeMarginDetail>();
            this.FuturisticBusinessTypes = new HashSet<FuturisticBusinessType>();
            this.FuturisticItemThresholdQties = new HashSet<FuturisticItemThresholdQty>();
            this.ItemThresholdQtyDetails = new HashSet<ItemThresholdQtyDetail>();
        }
    
        public int BusinessTypeID { get; set; }
        public string BusinessTypeName { get; set; }
        public string OrgId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreadtedById { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessTypeMarginDetail> BusinessTypeMarginDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuturisticBusinessType> FuturisticBusinessTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuturisticItemThresholdQty> FuturisticItemThresholdQties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemThresholdQtyDetail> ItemThresholdQtyDetails { get; set; }
    }
}
