//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditTypeMarginDetail
    {
        public int ID { get; set; }
        public string OrgId { get; set; }
        public Nullable<int> CreditTypeID { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public string BranchID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> FrmEffectiveDate { get; set; }
        public string FrmEffectiveTime { get; set; }
        public Nullable<System.DateTime> ToEffectiveDate { get; set; }
        public string ToEffectiveTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
    
        public virtual tblSysBranch tblSysBranch { get; set; }
    }
}
