//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCQuantityAllocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DCQuantityAllocation()
        {
            this.DCQtyAllocationItemWarehouseMaps = new HashSet<DCQtyAllocationItemWarehouseMap>();
        }
    
        public int ID { get; set; }
        public string DCNo { get; set; }
        public string RequisitionNumber { get; set; }
        public Nullable<int> ItemDetailsReqNumber { get; set; }
        public string ItemCode { get; set; }
        public decimal AllocatedQuantity { get; set; }
        public decimal Rate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Status { get; set; }
        public int CreatedID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
        public string BranchID { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCQtyAllocationItemWarehouseMap> DCQtyAllocationItemWarehouseMaps { get; set; }
    }
}
