//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverycenterBranchMap
    {
        public int DeliverycenterBranchMapID { get; set; }
        public string OrgID { get; set; }
        public string BranchID { get; set; }
        public int DelivercenterID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SourceOfUpdate { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
    
        public virtual tblSysBranch tblSysBranch { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
        public virtual tblSysOrganization tblSysOrganization { get; set; }
    }
}
