//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentUpload
    {
        public int ID { get; set; }
        public string GINID { get; set; }
        public string GPNumber { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public string ScreenName { get; set; }
        public string OrgID { get; set; }
        public string Ordernumber { get; set; }
        public string PartyID { get; set; }
        public string ConvertedFile { get; set; }
        public string FileExtension { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public bool IsTallyUpdated { get; set; }
        public string SourceOfUpdate { get; set; }
    
        public virtual tblGatePass tblGatePass { get; set; }
        public virtual tblGoodsInwardNote tblGoodsInwardNote { get; set; }
    }
}
