//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgersOpeningBalance
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string BillNumber { get; set; }
        public string OrgID { get; set; }
        public string BranchID { get; set; }
        public string LedgerID { get; set; }
        public string UnderLedgerType { get; set; }
        public Nullable<decimal> DrPendingAmt { get; set; }
        public Nullable<decimal> CrPendingAmt { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
