//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MWBTCustomerAppEntities : DbContext
    {
        public MWBTCustomerAppEntities()
            : base("name=MWBTCustomerAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountGroupDetail> AccountGroupDetails { get; set; }
        public virtual DbSet<BasicExpensesDetail> BasicExpensesDetails { get; set; }
        public virtual DbSet<BusinessTypeMarginDetail> BusinessTypeMarginDetails { get; set; }
        public virtual DbSet<BusinessType> BusinessTypes { get; set; }
        public virtual DbSet<CreditTypeMarginDetail> CreditTypeMarginDetails { get; set; }
        public virtual DbSet<CreditType> CreditTypes { get; set; }
        public virtual DbSet<CurrencyDenominationType> CurrencyDenominationTypes { get; set; }
        public virtual DbSet<DCQtyAllocationItemWarehouseMap> DCQtyAllocationItemWarehouseMaps { get; set; }
        public virtual DbSet<DCQuantityAllocation> DCQuantityAllocations { get; set; }
        public virtual DbSet<DeliverycenterBranchMap> DeliverycenterBranchMaps { get; set; }
        public virtual DbSet<DenominationMapWithTran> DenominationMapWithTrans { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DiscountsExpenseDetail> DiscountsExpenseDetails { get; set; }
        public virtual DbSet<DiscrepencyDetail> DiscrepencyDetails { get; set; }
        public virtual DbSet<DocumentsList> DocumentsLists { get; set; }
        public virtual DbSet<DocumentsSetting> DocumentsSettings { get; set; }
        public virtual DbSet<DocumentUpload> DocumentUploads { get; set; }
        public virtual DbSet<FranchiseMarginDetail> FranchiseMarginDetails { get; set; }
        public virtual DbSet<FreightExpenseDetail> FreightExpenseDetails { get; set; }
        public virtual DbSet<FumigationDetail> FumigationDetails { get; set; }
        public virtual DbSet<FumigationItemWrhsDetail> FumigationItemWrhsDetails { get; set; }
        public virtual DbSet<FuturisticBusinessType> FuturisticBusinessTypes { get; set; }
        public virtual DbSet<FuturisticCreditType> FuturisticCreditTypes { get; set; }
        public virtual DbSet<FuturisticItemThresholdQty> FuturisticItemThresholdQties { get; set; }
        public virtual DbSet<ItemThresholdQtyDetail> ItemThresholdQtyDetails { get; set; }
        public virtual DbSet<LedgersOpeningBalance> LedgersOpeningBalances { get; set; }
        public virtual DbSet<OfferPriceDetail> OfferPriceDetails { get; set; }
        public virtual DbSet<RateTransactionDetail> RateTransactionDetails { get; set; }
        public virtual DbSet<SalesManAreaMappingChild> SalesManAreaMappingChilds { get; set; }
        public virtual DbSet<SalesManAreaMappingParent> SalesManAreaMappingParents { get; set; }
        public virtual DbSet<tblAccessRight> tblAccessRights { get; set; }
        public virtual DbSet<tblAccountContraBillWithDetail> tblAccountContraBillWithDetails { get; set; }
        public virtual DbSet<tblAccountContraDetail> tblAccountContraDetails { get; set; }
        public virtual DbSet<tblAccountCreditNoteDetail> tblAccountCreditNoteDetails { get; set; }
        public virtual DbSet<tblAccountCreditNoteItemDetail> tblAccountCreditNoteItemDetails { get; set; }
        public virtual DbSet<tblAccountCreditNoteWithBillDetail> tblAccountCreditNoteWithBillDetails { get; set; }
        public virtual DbSet<tblAccountDebitNoteDetail> tblAccountDebitNoteDetails { get; set; }
        public virtual DbSet<tblAccountDebitNoteItemDetail> tblAccountDebitNoteItemDetails { get; set; }
        public virtual DbSet<tblAccountDebitNoteWithBillDetail> tblAccountDebitNoteWithBillDetails { get; set; }
        public virtual DbSet<tblAccountGroup> tblAccountGroups { get; set; }
        public virtual DbSet<tblAccountGroupMaster> tblAccountGroupMasters { get; set; }
        public virtual DbSet<tblAccountLedger> tblAccountLedgers { get; set; }
        public virtual DbSet<tblAccountPaymentDetail> tblAccountPaymentDetails { get; set; }
        public virtual DbSet<tblAccountPaymentWithBillDetail> tblAccountPaymentWithBillDetails { get; set; }
        public virtual DbSet<tblAccountReceiptDetail> tblAccountReceiptDetails { get; set; }
        public virtual DbSet<tblAccountReceiptWithBillDetail> tblAccountReceiptWithBillDetails { get; set; }
        public virtual DbSet<tblActivity> tblActivities { get; set; }
        public virtual DbSet<tblAdminConfiguration> tblAdminConfigurations { get; set; }
        public virtual DbSet<tblArea> tblAreas { get; set; }
        public virtual DbSet<tblBatch> tblBatches { get; set; }
        public virtual DbSet<tblBrand> tblBrands { get; set; }
        public virtual DbSet<tblCart> tblCarts { get; set; }
        public virtual DbSet<tblCartItem> tblCartItems { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCategoryType> tblCategoryTypes { get; set; }
        public virtual DbSet<tblChannelPartnerMapping> tblChannelPartnerMappings { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblCompanyType> tblCompanyTypes { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblCustomerCreditDetail> tblCustomerCreditDetails { get; set; }
        public virtual DbSet<tblCustomerType> tblCustomerTypes { get; set; }
        public virtual DbSet<tblCustomerVendorDetail> tblCustomerVendorDetails { get; set; }
        public virtual DbSet<tblDebtorsAreaDetail> tblDebtorsAreaDetails { get; set; }
        public virtual DbSet<tblDebtorsDetail> tblDebtorsDetails { get; set; }
        public virtual DbSet<tblDebtorsPlaceDetail> tblDebtorsPlaceDetails { get; set; }
        public virtual DbSet<tblDeliveryNote> tblDeliveryNotes { get; set; }
        public virtual DbSet<tblDeliveryNoteItem> tblDeliveryNoteItems { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblDiscount> tblDiscounts { get; set; }
        public virtual DbSet<tblDistrict> tblDistricts { get; set; }
        public virtual DbSet<tblGatePass> tblGatePasses { get; set; }
        public virtual DbSet<tblGatePassItem> tblGatePassItems { get; set; }
        public virtual DbSet<tblGoodsInwardNote> tblGoodsInwardNotes { get; set; }
        public virtual DbSet<tblGoodsInwardNoteItem> tblGoodsInwardNoteItems { get; set; }
        public virtual DbSet<tblGRN> tblGRNs { get; set; }
        public virtual DbSet<tblGRNItem> tblGRNItems { get; set; }
        public virtual DbSet<tblHOBranchPriceDetail> tblHOBranchPriceDetails { get; set; }
        public virtual DbSet<tblHOMasterPriceDetail> tblHOMasterPriceDetails { get; set; }
        public virtual DbSet<tblHSNCode> tblHSNCodes { get; set; }
        public virtual DbSet<tblItem> tblItems { get; set; }
        public virtual DbSet<tblItemCompany> tblItemCompanies { get; set; }
        public virtual DbSet<tblItemImageDetail> tblItemImageDetails { get; set; }
        public virtual DbSet<tblItemMapping> tblItemMappings { get; set; }
        public virtual DbSet<tblItemMappingWithCESS> tblItemMappingWithCESSes { get; set; }
        public virtual DbSet<tblItemMovement> tblItemMovements { get; set; }
        public virtual DbSet<tblItemParameterMap> tblItemParameterMaps { get; set; }
        public virtual DbSet<tblItemRate> tblItemRates { get; set; }
        public virtual DbSet<tblItemStockTransferDestination> tblItemStockTransferDestinations { get; set; }
        public virtual DbSet<tblItemStockTransferHeader> tblItemStockTransferHeaders { get; set; }
        public virtual DbSet<tblItemStockTransferSource> tblItemStockTransferSources { get; set; }
        public virtual DbSet<tblItemSupplierMapping> tblItemSupplierMappings { get; set; }
        public virtual DbSet<tblItemToItemTracking> tblItemToItemTrackings { get; set; }
        public virtual DbSet<tblItemWarehouseMap> tblItemWarehouseMaps { get; set; }
        public virtual DbSet<tblLedgerType> tblLedgerTypes { get; set; }
        public virtual DbSet<tblNotification> tblNotifications { get; set; }
        public virtual DbSet<tblOrganizationWarehouseMap> tblOrganizationWarehouseMaps { get; set; }
        public virtual DbSet<tblPacketSizeDetail> tblPacketSizeDetails { get; set; }
        public virtual DbSet<tblParameter> tblParameters { get; set; }
        public virtual DbSet<tblPaymentReceipt> tblPaymentReceipts { get; set; }
        public virtual DbSet<tblPCN_Details> tblPCN_Details { get; set; }
        public virtual DbSet<tblPercentageStructure> tblPercentageStructures { get; set; }
        public virtual DbSet<tblPNCN> tblPNCNs { get; set; }
        public virtual DbSet<tblPOQuotation> tblPOQuotations { get; set; }
        public virtual DbSet<tblPOQuotationSupplier> tblPOQuotationSuppliers { get; set; }
        public virtual DbSet<tblProcessitem_Master> tblProcessitem_Master { get; set; }
        public virtual DbSet<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        public virtual DbSet<tblPurchaseOrderInvoice> tblPurchaseOrderInvoices { get; set; }
        public virtual DbSet<tblPurchaseOrderInvoiceItemDetail> tblPurchaseOrderInvoiceItemDetails { get; set; }
        public virtual DbSet<tblPurchaseOrderWithItem> tblPurchaseOrderWithItems { get; set; }
        public virtual DbSet<tblPurchaseRequisition> tblPurchaseRequisitions { get; set; }
        public virtual DbSet<tblPurchaseRequisitionItemsDetail> tblPurchaseRequisitionItemsDetails { get; set; }
        public virtual DbSet<tblRack> tblRacks { get; set; }
        public virtual DbSet<tblReason> tblReasons { get; set; }
        public virtual DbSet<tblReceiptDetail> tblReceiptDetails { get; set; }
        public virtual DbSet<tblReceiptWithBillDetail> tblReceiptWithBillDetails { get; set; }
        public virtual DbSet<tblRouteMapping> tblRouteMappings { get; set; }
        public virtual DbSet<tblRouteMappingDetail> tblRouteMappingDetails { get; set; }
        public virtual DbSet<tblSalesChannelType> tblSalesChannelTypes { get; set; }
        public virtual DbSet<tblSalesmanDetail> tblSalesmanDetails { get; set; }
        public virtual DbSet<tblSalesOrder> tblSalesOrders { get; set; }
        public virtual DbSet<tblSalesOrderCashTransaction> tblSalesOrderCashTransactions { get; set; }
        public virtual DbSet<tblSalesOrderInvoice> tblSalesOrderInvoices { get; set; }
        public virtual DbSet<tblSalesOrderInvoiceItemDetail> tblSalesOrderInvoiceItemDetails { get; set; }
        public virtual DbSet<tblSalesOrderItemWarehouseMap> tblSalesOrderItemWarehouseMaps { get; set; }
        public virtual DbSet<tblSalesOrderWithItem> tblSalesOrderWithItems { get; set; }
        public virtual DbSet<tblSPDocument> tblSPDocuments { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblStateWithCity> tblStateWithCities { get; set; }
        public virtual DbSet<tblStickerDetail> tblStickerDetails { get; set; }
        public virtual DbSet<tblStockTransferHeader> tblStockTransferHeaders { get; set; }
        public virtual DbSet<tblStockTransferLineItem> tblStockTransferLineItems { get; set; }
        public virtual DbSet<tblSubAccountGroupMaster> tblSubAccountGroupMasters { get; set; }
        public virtual DbSet<tblSubCategory> tblSubCategories { get; set; }
        public virtual DbSet<tblSubMenuRoleMap> tblSubMenuRoleMaps { get; set; }
        public virtual DbSet<tblSysBranch> tblSysBranches { get; set; }
        public virtual DbSet<tblSysMainMenu> tblSysMainMenus { get; set; }
        public virtual DbSet<tblSysOrganization> tblSysOrganizations { get; set; }
        public virtual DbSet<tblSysOrganizationMap> tblSysOrganizationMaps { get; set; }
        public virtual DbSet<tblSysRole> tblSysRoles { get; set; }
        public virtual DbSet<tblSysSubMenu> tblSysSubMenus { get; set; }
        public virtual DbSet<tblSystemDetail> tblSystemDetails { get; set; }
        public virtual DbSet<tblSysUser> tblSysUsers { get; set; }
        public virtual DbSet<tblTaxationType> tblTaxationTypes { get; set; }
        public virtual DbSet<tblTaxCESS> tblTaxCESSes { get; set; }
        public virtual DbSet<tblTransitItem> tblTransitItems { get; set; }
        public virtual DbSet<tblTransitItemDetail> tblTransitItemDetails { get; set; }
        public virtual DbSet<tblUnitQuantity> tblUnitQuantities { get; set; }
        public virtual DbSet<tblUOM> tblUOMs { get; set; }
        public virtual DbSet<tblUserAreaofService> tblUserAreaofServices { get; set; }
        public virtual DbSet<tblUserDocument> tblUserDocuments { get; set; }
        public virtual DbSet<tblUserMapping> tblUserMappings { get; set; }
        public virtual DbSet<tblUserWarehouseMap> tblUserWarehouseMaps { get; set; }
        public virtual DbSet<tblVoucherType> tblVoucherTypes { get; set; }
        public virtual DbSet<tblWarehouse> tblWarehouses { get; set; }
        public virtual DbSet<tblWarehouseToWarehouseTracking> tblWarehouseToWarehouseTrackings { get; set; }
        public virtual DbSet<TypeOfExpens> TypeOfExpenses { get; set; }
        public virtual DbSet<VirtualWarehouseDetail> VirtualWarehouseDetails { get; set; }
        public virtual DbSet<tblPlan> tblPlans { get; set; }
        public virtual DbSet<tblSysChannelPartner> tblSysChannelPartners { get; set; }
        public virtual DbSet<tblAccessControl> tblAccessControls { get; set; }
        public virtual DbSet<tblAccessControlItem> tblAccessControlItems { get; set; }
        public virtual DbSet<tblAdminSetting> tblAdminSettings { get; set; }
        public virtual DbSet<tblBranchDocument> tblBranchDocuments { get; set; }
        public virtual DbSet<tblEmailTemplate> tblEmailTemplates { get; set; }
        public virtual DbSet<tblSMSTemplate> tblSMSTemplates { get; set; }
        public virtual DbSet<tblWhatsappTemplate> tblWhatsappTemplates { get; set; }
        public virtual DbSet<tblTemplateImage> tblTemplateImages { get; set; }
        public virtual DbSet<tblUserTemplate> tblUserTemplates { get; set; }
        public virtual DbSet<tblOrgSystemDetail> tblOrgSystemDetails { get; set; }
        public virtual DbSet<tblTallySyncError> tblTallySyncErrors { get; set; }
        public virtual DbSet<tblReligion> tblReligions { get; set; }
        public virtual DbSet<tblTaxLedger> tblTaxLedgers { get; set; }
        public virtual DbSet<tblWeekoff> tblWeekoffs { get; set; }
    }
}
