//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountGroup
    {
        public int AccountGroup { get; set; }
        public int AccountGroupMasterID { get; set; }
        public string AccountName { get; set; }
        public string SaleOrPurchase { get; set; }
        public Nullable<bool> IsSubAccountGroup { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsTallyUpdated { get; set; }
    
        public virtual tblAccountGroupMaster tblAccountGroupMaster { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
    }
}
