//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountDebitNoteItemDetail
    {
        public int ID { get; set; }
        public string DebitNoteID { get; set; }
        public Nullable<System.Guid> DebitNoteWithID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> DeliveredQTY { get; set; }
        public Nullable<decimal> ReturnQTY { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string InvoiceNo { get; set; }
        public string VoucherTypeNo { get; set; }
        public string OrgID { get; set; }
        public int WarehouseID { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsTallyUpdated { get; set; }
        public int CreatedByID { get; set; }
        public string SourceOfUpdate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TaxValue { get; set; }
        public Nullable<decimal> NetValue { get; set; }
        public Nullable<decimal> GST { get; set; }
    
        public virtual tblAccountDebitNoteDetail tblAccountDebitNoteDetail { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblReason tblReason { get; set; }
    }
}
