//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountReceiptWithBillDetail
    {
        public int ID { get; set; }
        public System.Guid ReceiptWithBillID { get; set; }
        public string ReceiptID { get; set; }
        public string CustID { get; set; }
        public string OutstandingAmt { get; set; }
        public string OrgID { get; set; }
        public string BillType { get; set; }
        public string BillNo { get; set; }
        public string Billdatetime { get; set; }
        public Nullable<decimal> TallyAmount { get; set; }
        public Nullable<decimal> Discountamount { get; set; }
        public Nullable<decimal> Billamount { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<bool> IsTallyUpdated { get; set; }
        public string SourceOfUpdate { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> TallySync { get; set; }
        public string Status { get; set; }
        public string ParentVoucherName { get; set; }
        public Nullable<decimal> OrgValueCr { get; set; }
    
        public virtual tblAccountReceiptDetail tblAccountReceiptDetail { get; set; }
        public virtual tblSysOrganization tblSysOrganization { get; set; }
    }
}
