//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdminSetting
    {
        public int ID { get; set; }
        public string MarketingEmailID { get; set; }
        public string Password { get; set; }
        public bool AutoSyncTally { get; set; }
        public string MailHost { get; set; }
        public string SendingPort { get; set; }
        public string SMSAPIKey { get; set; }
        public string TransactionalBaseURL { get; set; }
        public string TansactionalSenderID { get; set; }
        public string PromotionSenderID { get; set; }
        public string PromotionalBaseURL { get; set; }
        public string OrgID { get; set; }
        public Nullable<bool> EnableSSL { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SORegister { get; set; }
        public string GroupName { get; set; }
        public bool PriceSyncType { get; set; }
    }
}
