//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCart()
        {
            this.tblCartItems = new HashSet<tblCartItem>();
        }
    
        public int CartID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public Nullable<int> CreditType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCartItem> tblCartItems { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
    }
}
