//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeliveryNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDeliveryNote()
        {
            this.tblDeliveryNoteItems = new HashSet<tblDeliveryNoteItem>();
        }
    
        public int ID { get; set; }
        public string DeliveryNoteCode { get; set; }
        public string GatePassCode { get; set; }
        public string OrgID { get; set; }
        public string SalesOrderNumber { get; set; }
        public Nullable<System.DateTime> DeliveryNoteDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LoadStartDateTime { get; set; }
        public Nullable<System.DateTime> LoadEndDateTime { get; set; }
        public string LoadingStatus { get; set; }
        public bool IsTallyUpdated { get; set; }
        public string SourceOfUpdate { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string Remark { get; set; }
        public string DNType { get; set; }
        public string DNTypeNum { get; set; }
        public string VoucherTypeNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeliveryNoteItem> tblDeliveryNoteItems { get; set; }
        public virtual tblVoucherType tblVoucherType { get; set; }
        public virtual tblGatePass tblGatePass { get; set; }
        public virtual tblSalesOrder tblSalesOrder { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        public virtual tblSysOrganization tblSysOrganization { get; set; }
    }
}
