//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGRN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGRN()
        {
            this.tblGRNItems = new HashSet<tblGRNItem>();
            this.tblItemWarehouseMaps = new HashSet<tblItemWarehouseMap>();
            this.tblStickerDetails = new HashSet<tblStickerDetail>();
        }
    
        public int ID { get; set; }
        public string GRNNumber { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string OrgId { get; set; }
        public string BranchId { get; set; }
        public string InvoiceNumber { get; set; }
        public string DeliveryNoteCode { get; set; }
        public string CustID { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public Nullable<System.DateTime> GRNDate { get; set; }
        public string VehicalNumber { get; set; }
        public string DriverName { get; set; }
        public string DriverNumber { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> TareWeight { get; set; }
        public Nullable<decimal> FrieghtCharges { get; set; }
        public Nullable<decimal> LoadingCharges { get; set; }
        public string DeliveryType { get; set; }
        public bool IsTallyUpdated { get; set; }
        public string SourceOfUpdate { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> UnloadStartTime { get; set; }
        public Nullable<System.DateTime> UnloadEndTime { get; set; }
        public string Status { get; set; }
        public string VehicleComments { get; set; }
        public string VoucherTypeNo { get; set; }
    
        public virtual tblCustomerVendorDetail tblCustomerVendorDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGRNItem> tblGRNItems { get; set; }
        public virtual tblVoucherType tblVoucherType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemWarehouseMap> tblItemWarehouseMaps { get; set; }
        public virtual tblPurchaseOrder tblPurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStickerDetail> tblStickerDetails { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
    }
}
