//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGoodsInwardNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGoodsInwardNote()
        {
            this.DocumentUploads = new HashSet<DocumentUpload>();
            this.tblGoodsInwardNoteItems = new HashSet<tblGoodsInwardNoteItem>();
            this.tblPurchaseOrderInvoices = new HashSet<tblPurchaseOrderInvoice>();
        }
    
        public string GINID { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string SupplierId { get; set; }
        public string BranchId { get; set; }
        public string OrgId { get; set; }
        public string VoucherTypeNo { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> GrossSupplierWeight { get; set; }
        public Nullable<decimal> TareSupplierWeight { get; set; }
        public Nullable<decimal> NetSupplierWeight { get; set; }
        public Nullable<decimal> GrossInwardWeight { get; set; }
        public Nullable<decimal> TareWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public string LRNumber { get; set; }
        public string DriverName { get; set; }
        public string DriverMobileNumber { get; set; }
        public string DriverLicenseNumber { get; set; }
        public string TransporterName { get; set; }
        public string VehicleRegisterationNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
        public string SourceOfUpdate { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentUpload> DocumentUploads { get; set; }
        public virtual tblCustomerVendorDetail tblCustomerVendorDetail { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoodsInwardNoteItem> tblGoodsInwardNoteItems { get; set; }
        public virtual tblPurchaseOrder tblPurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderInvoice> tblPurchaseOrderInvoices { get; set; }
        public virtual tblVoucherType tblVoucherType { get; set; }
    }
}
