//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGatePassItem
    {
        public int ID { get; set; }
        public string GatePassCode { get; set; }
        public string SalesOrderNumber { get; set; }
        public Nullable<System.Guid> SalesOrderWithItemID { get; set; }
        public string ItemCode { get; set; }
        public decimal Ordered { get; set; }
        public decimal ToBeDeliveredQTY { get; set; }
        public string OrgID { get; set; }
        public int WarehouseID { get; set; }
        public int BatchID { get; set; }
        public int Priority { get; set; }
        public Nullable<decimal> DeliveredQTY { get; set; }
        public string Status { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public string SourceOfUpdate { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SOType { get; set; }
        public string SOTypeNum { get; set; }
        public Nullable<int> UnloadPriority { get; set; }
    
        public virtual tblBatch tblBatch { get; set; }
        public virtual tblGatePass tblGatePass { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblReason tblReason { get; set; }
        public virtual tblSalesOrder tblSalesOrder { get; set; }
        public virtual tblSalesOrderWithItem tblSalesOrderWithItem { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
    }
}
