//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemStockTransferSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblItemStockTransferSource()
        {
            this.tblItemStockTransferDestinations = new HashSet<tblItemStockTransferDestination>();
        }
    
        public int ItemStockTransferSourceID { get; set; }
        public Nullable<int> ItemStockTransferHeaderID { get; set; }
        public string BT_Num { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> RequiredQuantity { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsTallyUpdated { get; set; }
        public string Status { get; set; }
        public bool IsFIFOSkipped { get; set; }
        public int WarehouseID { get; set; }
        public Nullable<decimal> QtyTransfered { get; set; }
        public string ApprovalStatus { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblBatch tblBatch { get; set; }
        public virtual tblItem tblItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemStockTransferDestination> tblItemStockTransferDestinations { get; set; }
        public virtual tblItemStockTransferHeader tblItemStockTransferHeader { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
    }
}
