//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemMovement
    {
        public int ID { get; set; }
        public string ItemCode { get; set; }
        public string TransactionType { get; set; }
        public string SalesOrderNumber { get; set; }
        public Nullable<System.Guid> SalesOrderWithItemID { get; set; }
        public Nullable<int> SaleQty { get; set; }
        public Nullable<int> DeliveredQty { get; set; }
        public Nullable<int> PendingQty { get; set; }
        public Nullable<int> NegativeQty { get; set; }
        public Nullable<int> ReceivedQty { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string OrgID { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SourceOfUpdate { get; set; }
    
        public virtual tblBatch tblBatch { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblSalesOrder tblSalesOrder { get; set; }
        public virtual tblSalesOrderWithItem tblSalesOrderWithItem { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
    }
}
