//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemToItemTracking
    {
        public int ItemTrackingID { get; set; }
        public string SourceItemCode { get; set; }
        public decimal SourceAvailbaleQty { get; set; }
        public string SourcePacketSize { get; set; }
        public string SourceBagSize { get; set; }
        public Nullable<int> SourceBatchID { get; set; }
        public Nullable<int> SourceWarehouseID { get; set; }
        public Nullable<decimal> SourceNetQty { get; set; }
        public int DestinationWarehouseID { get; set; }
        public string DestinationItemCode { get; set; }
        public string DestinationPacketSize { get; set; }
        public string DestinationBagSize { get; set; }
        public decimal DestinationQty { get; set; }
        public Nullable<decimal> DestinationNetQty { get; set; }
        public Nullable<int> DestinationBatchID { get; set; }
        public string SourceOfUpdate { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
    
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
    }
}
