//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemSupplierMapping
    {
        public int ItemSupMappingID { get; set; }
        public string ItemCode { get; set; }
        public string CustID { get; set; }
        public string SourceOfUpdate { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsMapped { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<int> DelivercenterID { get; set; }
        public string Choice { get; set; }
        public string VendorType { get; set; }
    
        public virtual tblCustomerVendorDetail tblCustomerVendorDetail { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
    }
}
