//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPNCN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPNCN()
        {
            this.tblPCN_Details = new HashSet<tblPCN_Details>();
        }
    
        public int pcn_idpk { get; set; }
        public string pcn_num { get; set; }
        public string Voucher_IDFK { get; set; }
        public Nullable<System.DateTime> pcn_date { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<decimal> Quantity_Qtl { get; set; }
        public string OrgID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> isTallyupdated { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPCN_Details> tblPCN_Details { get; set; }
    }
}
