//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrderInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPurchaseOrderInvoice()
        {
            this.tblPurchaseOrderInvoiceItemDetails = new HashSet<tblPurchaseOrderInvoiceItemDetail>();
        }
    
        public int ID { get; set; }
        public string POInvoiceReferenceNumber { get; set; }
        public string PaymentStatus { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string GINID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public string Shipping_Address { get; set; }
        public string Billing_Address { get; set; }
        public string OrgID { get; set; }
        public string SuppID { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> GSTOnFreightAmount { get; set; }
        public Nullable<decimal> InvoiceFreightChargesTotal { get; set; }
        public Nullable<decimal> Loading_UnloadingTotal { get; set; }
        public Nullable<decimal> OtherExpenses { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public bool IsTallyUpdated { get; set; }
        public Nullable<int> TallyUpdatedByID { get; set; }
        public Nullable<System.DateTime> TallyUpdatedDate { get; set; }
        public string SourceOfUpdate { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> TareSupplierWeight { get; set; }
        public Nullable<decimal> TareInwardWeight { get; set; }
        public Nullable<decimal> NetSupplierWeight { get; set; }
        public Nullable<decimal> NetInwardWeight { get; set; }
        public string UnitwiseQty { get; set; }
        public string VoucherTypeNo { get; set; }
        public Nullable<decimal> TCSPercentage { get; set; }
        public Nullable<decimal> TCSValue { get; set; }
        public Nullable<decimal> InsuranceCharges { get; set; }
    
        public virtual tblCustomerVendorDetail tblCustomerVendorDetail { get; set; }
        public virtual tblGoodsInwardNote tblGoodsInwardNote { get; set; }
        public virtual tblPurchaseOrder tblPurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderInvoiceItemDetail> tblPurchaseOrderInvoiceItemDetails { get; set; }
        public virtual tblVoucherType tblVoucherType { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        public virtual tblSysOrganization tblSysOrganization { get; set; }
    }
}
