//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPurchaseOrder()
        {
            this.tblGoodsInwardNotes = new HashSet<tblGoodsInwardNote>();
            this.tblGRNs = new HashSet<tblGRN>();
            this.tblPurchaseOrderWithItems = new HashSet<tblPurchaseOrderWithItem>();
            this.tblTransitItems = new HashSet<tblTransitItem>();
            this.tblPurchaseOrderInvoices = new HashSet<tblPurchaseOrderInvoice>();
        }
    
        public int ID { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public System.DateTime PurchasOrderDate { get; set; }
        public Nullable<System.DateTime> PurchaseOrderExpectedDate { get; set; }
        public Nullable<bool> PurchaseOrderSource { get; set; }
        public string PurchaseRequisitionNumber { get; set; }
        public string SupplierID { get; set; }
        public string OrgId { get; set; }
        public string BranchId { get; set; }
        public Nullable<int> WareHouseId { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public string IsPurchaseOrderAddTally { get; set; }
        public Nullable<decimal> FreightQty { get; set; }
        public Nullable<decimal> FreightRate { get; set; }
        public Nullable<decimal> FreightCharges { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<int> TotalItemCount { get; set; }
        public string Comments { get; set; }
        public bool IsTallyUpdated { get; set; }
        public string SourceOfUpdate { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SalesOrderNumber { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountVal { get; set; }
        public string VoucherTypeNo { get; set; }
        public string SMSStatus { get; set; }
        public string PurchaseType { get; set; }
    
        public virtual tblCustomerVendorDetail tblCustomerVendorDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoodsInwardNote> tblGoodsInwardNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGRN> tblGRNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderWithItem> tblPurchaseOrderWithItems { get; set; }
        public virtual tblPurchaseRequisition tblPurchaseRequisition { get; set; }
        public virtual tblSalesOrder tblSalesOrder { get; set; }
        public virtual tblSysBranch tblSysBranch { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransitItem> tblTransitItems { get; set; }
        public virtual tblVoucherType tblVoucherType { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderInvoice> tblPurchaseOrderInvoices { get; set; }
        public virtual tblSysUser tblSysUser2 { get; set; }
        public virtual tblSysUser tblSysUser3 { get; set; }
        public virtual tblSysOrganization tblSysOrganization { get; set; }
    }
}
