//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSalesOrder()
        {
            this.tblDeliveryNotes = new HashSet<tblDeliveryNote>();
            this.tblGatePasses = new HashSet<tblGatePass>();
            this.tblGatePassItems = new HashSet<tblGatePassItem>();
            this.tblItemMovements = new HashSet<tblItemMovement>();
            this.tblPurchaseOrders = new HashSet<tblPurchaseOrder>();
            this.tblSalesOrderCashTransactions = new HashSet<tblSalesOrderCashTransaction>();
            this.tblSalesOrderInvoices = new HashSet<tblSalesOrderInvoice>();
            this.tblSalesOrderItemWarehouseMaps = new HashSet<tblSalesOrderItemWarehouseMap>();
            this.tblSalesOrderWithItems = new HashSet<tblSalesOrderWithItem>();
        }
    
        public int ID { get; set; }
        public string SalesOrderNumber { get; set; }
        public Nullable<bool> IsDirectSO { get; set; }
        public string SalesDatetime { get; set; }
        public string OrgID { get; set; }
        public string CustID { get; set; }
        public Nullable<int> SalesmanID { get; set; }
        public Nullable<int> BrokerID { get; set; }
        public string VoucherTypeNo { get; set; }
        public string SignatureImage { get; set; }
        public Nullable<bool> IsBulkSale { get; set; }
        public string SalesType { get; set; }
        public string SMSStatus { get; set; }
        public bool IsTallyUpdated { get; set; }
        public Nullable<bool> IsDirectSale { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public string Status { get; set; }
        public string ApprovalStatus { get; set; }
        public string RegistrationType { get; set; }
        public decimal TotalItemCount { get; set; }
        public string TransType { get; set; }
        public string Comments { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> RSalesDatetime { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<bool> IsDelivaryNote { get; set; }
        public Nullable<bool> IsGatePassEntered { get; set; }
        public string URDNumber { get; set; }
        public string BillingAddress { get; set; }
        public string BarCode { get; set; }
        public string SourceOfUpdate { get; set; }
        public string BranchID { get; set; }
        public Nullable<bool> IsDiscountRangeExceeded { get; set; }
        public string RejectionRemark { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsCreditLimitExceeded { get; set; }
        public Nullable<bool> IsCreditDaysExceeded { get; set; }
        public Nullable<bool> IsBillsExceeded { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string PANNumber { get; set; }
        public string DCNo { get; set; }
        public string OrderGivenPersonName { get; set; }
        public Nullable<int> BusinessTypeId { get; set; }
        public Nullable<decimal> BusinessTypeValue { get; set; }
        public Nullable<int> CreditTypeId { get; set; }
        public Nullable<decimal> CreditTypeValue { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public Nullable<bool> TallySync { get; set; }
        public string RetSOName { get; set; }
        public string RetSOSignature { get; set; }
        public bool IsEdited { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
    
        public virtual tblCustomerVendorDetail tblCustomerVendorDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeliveryNote> tblDeliveryNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGatePass> tblGatePasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGatePassItem> tblGatePassItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemMovement> tblItemMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        public virtual tblSysBranch tblSysBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderCashTransaction> tblSalesOrderCashTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderInvoice> tblSalesOrderInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderItemWarehouseMap> tblSalesOrderItemWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderWithItem> tblSalesOrderWithItems { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        public virtual tblSysUser tblSysUser2 { get; set; }
        public virtual tblSysUser tblSysUser3 { get; set; }
        public virtual tblVoucherType tblVoucherType { get; set; }
        public virtual tblSysOrganization tblSysOrganization { get; set; }
    }
}
