//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysBranch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSysBranch()
        {
            this.BasicExpensesDetails = new HashSet<BasicExpensesDetail>();
            this.BusinessTypeMarginDetails = new HashSet<BusinessTypeMarginDetail>();
            this.CreditTypeMarginDetails = new HashSet<CreditTypeMarginDetail>();
            this.DeliverycenterBranchMaps = new HashSet<DeliverycenterBranchMap>();
            this.DiscrepencyDetails = new HashSet<DiscrepencyDetail>();
            this.tblAccountContraDetails = new HashSet<tblAccountContraDetail>();
            this.tblAccountCreditNoteDetails = new HashSet<tblAccountCreditNoteDetail>();
            this.tblAccountDebitNoteDetails = new HashSet<tblAccountDebitNoteDetail>();
            this.tblHOBranchPriceDetails = new HashSet<tblHOBranchPriceDetail>();
            this.tblItemMappings = new HashSet<tblItemMapping>();
            this.tblItemWarehouseMaps = new HashSet<tblItemWarehouseMap>();
            this.tblOrganizationWarehouseMaps = new HashSet<tblOrganizationWarehouseMap>();
            this.tblPurchaseOrders = new HashSet<tblPurchaseOrder>();
            this.tblPurchaseRequisitions = new HashSet<tblPurchaseRequisition>();
            this.tblSalesOrders = new HashSet<tblSalesOrder>();
            this.tblSysUsers = new HashSet<tblSysUser>();
            this.tblWarehouses = new HashSet<tblWarehouse>();
            this.tblVoucherTypes = new HashSet<tblVoucherType>();
            this.tblSysChannelPartners = new HashSet<tblSysChannelPartner>();
        }
    
        public string BranchID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string OrgID { get; set; }
        public string Phone { get; set; }
        public string ContactPerson { get; set; }
        public string Location { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string BillingLandmark { get; set; }
        public string ShippingLandmark { get; set; }
        public string BillingAddress { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string ShippingAddress { get; set; }
        public string MailingName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> FinancialYearStart { get; set; }
        public Nullable<System.DateTime> FinancialYearEnd { get; set; }
        public string BankName { get; set; }
        public string BankBranchName { get; set; }
        public string BankCity { get; set; }
        public string AlternateNumber { get; set; }
        public string ShippingPinCode { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string FSSAICode { get; set; }
        public string GST { get; set; }
        public string PANNumber { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public Nullable<bool> IsMappedToOrg { get; set; }
        public string MappedOrgID { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDatetime { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
        public Nullable<decimal> Quantitylimit { get; set; }
        public Nullable<int> ChannelTypeID { get; set; }
        public Nullable<int> AssociatedTo { get; set; }
        public Nullable<int> ParentChannelPartnerID { get; set; }
        public Nullable<int> BranchCity { get; set; }
        public Nullable<int> BranchState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicExpensesDetail> BasicExpensesDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessTypeMarginDetail> BusinessTypeMarginDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditTypeMarginDetail> CreditTypeMarginDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliverycenterBranchMap> DeliverycenterBranchMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscrepencyDetail> DiscrepencyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountContraDetail> tblAccountContraDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountCreditNoteDetail> tblAccountCreditNoteDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountDebitNoteDetail> tblAccountDebitNoteDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHOBranchPriceDetail> tblHOBranchPriceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemMapping> tblItemMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemWarehouseMap> tblItemWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrganizationWarehouseMap> tblOrganizationWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseRequisition> tblPurchaseRequisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrder> tblSalesOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysUser> tblSysUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWarehouse> tblWarehouses { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherType> tblVoucherTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysChannelPartner> tblSysChannelPartners { get; set; }
    }
}
