//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesOrderItemWarehouseMap
    {
        public int ID { get; set; }
        public System.Guid SalesOrderWithItemID { get; set; }
        public string SalesOrderNumber { get; set; }
        public string ItemCode { get; set; }
        public string OrgID { get; set; }
        public int WarehouseID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal QuantityOrdered { get; set; }
        public Nullable<bool> IsNegativeStock { get; set; }
        public string NegativeStockApprovalStatus { get; set; }
        public string NegativeStockApproveRemark { get; set; }
        public Nullable<bool> IsFIFOSkipped { get; set; }
        public string FIFOApprovalStatus { get; set; }
        public string FIFOApproveRemark { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
    
        public virtual tblBatch tblBatch { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblSalesOrder tblSalesOrder { get; set; }
        public virtual tblSalesOrderWithItem tblSalesOrderWithItem { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
    }
}
