//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSysUser()
        {
            this.DiscrepencyDetails = new HashSet<DiscrepencyDetail>();
            this.DiscrepencyDetails1 = new HashSet<DiscrepencyDetail>();
            this.tblAccessRights = new HashSet<tblAccessRight>();
            this.tblAccessRights1 = new HashSet<tblAccessRight>();
            this.tblAccessRights2 = new HashSet<tblAccessRight>();
            this.tblAccountGroups = new HashSet<tblAccountGroup>();
            this.tblAccountGroupMasters = new HashSet<tblAccountGroupMaster>();
            this.tblActivities = new HashSet<tblActivity>();
            this.tblActivities1 = new HashSet<tblActivity>();
            this.tblAdminConfigurations = new HashSet<tblAdminConfiguration>();
            this.tblAdminConfigurations1 = new HashSet<tblAdminConfiguration>();
            this.tblBatches = new HashSet<tblBatch>();
            this.tblBatches1 = new HashSet<tblBatch>();
            this.tblBrands = new HashSet<tblBrand>();
            this.tblBrands1 = new HashSet<tblBrand>();
            this.tblCarts = new HashSet<tblCart>();
            this.tblCategories = new HashSet<tblCategory>();
            this.tblCategories1 = new HashSet<tblCategory>();
            this.tblCustomerCreditDetails = new HashSet<tblCustomerCreditDetail>();
            this.tblCustomerVendorDetails = new HashSet<tblCustomerVendorDetail>();
            this.tblCustomerVendorDetails1 = new HashSet<tblCustomerVendorDetail>();
            this.tblCustomerVendorDetails2 = new HashSet<tblCustomerVendorDetail>();
            this.tblDebtorsAreaDetails = new HashSet<tblDebtorsAreaDetail>();
            this.tblDebtorsAreaDetails1 = new HashSet<tblDebtorsAreaDetail>();
            this.tblDebtorsPlaceDetails = new HashSet<tblDebtorsPlaceDetail>();
            this.tblDebtorsPlaceDetails1 = new HashSet<tblDebtorsPlaceDetail>();
            this.tblDeliveryNotes = new HashSet<tblDeliveryNote>();
            this.tblDeliveryNotes1 = new HashSet<tblDeliveryNote>();
            this.tblDeliveryNoteItems = new HashSet<tblDeliveryNoteItem>();
            this.tblDeliveryNoteItems1 = new HashSet<tblDeliveryNoteItem>();
            this.tblDiscounts = new HashSet<tblDiscount>();
            this.tblDiscounts1 = new HashSet<tblDiscount>();
            this.tblGatePasses = new HashSet<tblGatePass>();
            this.tblGatePasses1 = new HashSet<tblGatePass>();
            this.tblGatePassItems = new HashSet<tblGatePassItem>();
            this.tblGoodsInwardNotes = new HashSet<tblGoodsInwardNote>();
            this.tblGoodsInwardNotes1 = new HashSet<tblGoodsInwardNote>();
            this.tblGoodsInwardNoteItems = new HashSet<tblGoodsInwardNoteItem>();
            this.tblGoodsInwardNoteItems1 = new HashSet<tblGoodsInwardNoteItem>();
            this.tblGRNs = new HashSet<tblGRN>();
            this.tblGRNs1 = new HashSet<tblGRN>();
            this.tblGRNItems = new HashSet<tblGRNItem>();
            this.tblGRNItems1 = new HashSet<tblGRNItem>();
            this.tblHOBranchPriceDetails = new HashSet<tblHOBranchPriceDetail>();
            this.tblHOBranchPriceDetails1 = new HashSet<tblHOBranchPriceDetail>();
            this.tblHOMasterPriceDetails = new HashSet<tblHOMasterPriceDetail>();
            this.tblHOMasterPriceDetails1 = new HashSet<tblHOMasterPriceDetail>();
            this.tblHSNCodes = new HashSet<tblHSNCode>();
            this.tblHSNCodes1 = new HashSet<tblHSNCode>();
            this.tblItems = new HashSet<tblItem>();
            this.tblItems1 = new HashSet<tblItem>();
            this.tblItemCompanies = new HashSet<tblItemCompany>();
            this.tblItemCompanies1 = new HashSet<tblItemCompany>();
            this.tblItemMappingWithCESSes = new HashSet<tblItemMappingWithCESS>();
            this.tblItemMappingWithCESSes1 = new HashSet<tblItemMappingWithCESS>();
            this.tblItemMovements = new HashSet<tblItemMovement>();
            this.tblItemParameterMaps = new HashSet<tblItemParameterMap>();
            this.tblItemParameterMaps1 = new HashSet<tblItemParameterMap>();
            this.tblItemRates = new HashSet<tblItemRate>();
            this.tblItemRates1 = new HashSet<tblItemRate>();
            this.tblItemStockTransferDestinations = new HashSet<tblItemStockTransferDestination>();
            this.tblItemStockTransferHeaders = new HashSet<tblItemStockTransferHeader>();
            this.tblItemStockTransferSources = new HashSet<tblItemStockTransferSource>();
            this.tblItemSupplierMappings = new HashSet<tblItemSupplierMapping>();
            this.tblItemSupplierMappings1 = new HashSet<tblItemSupplierMapping>();
            this.tblItemToItemTrackings = new HashSet<tblItemToItemTracking>();
            this.tblItemToItemTrackings1 = new HashSet<tblItemToItemTracking>();
            this.tblItemWarehouseMaps = new HashSet<tblItemWarehouseMap>();
            this.tblItemWarehouseMaps1 = new HashSet<tblItemWarehouseMap>();
            this.tblNotifications = new HashSet<tblNotification>();
            this.tblOrganizationWarehouseMaps = new HashSet<tblOrganizationWarehouseMap>();
            this.tblOrganizationWarehouseMaps1 = new HashSet<tblOrganizationWarehouseMap>();
            this.tblPacketSizeDetails = new HashSet<tblPacketSizeDetail>();
            this.tblPacketSizeDetails1 = new HashSet<tblPacketSizeDetail>();
            this.tblParameters = new HashSet<tblParameter>();
            this.tblParameters1 = new HashSet<tblParameter>();
            this.tblPaymentReceipts = new HashSet<tblPaymentReceipt>();
            this.tblPaymentReceipts1 = new HashSet<tblPaymentReceipt>();
            this.tblPercentageStructures = new HashSet<tblPercentageStructure>();
            this.tblPercentageStructures1 = new HashSet<tblPercentageStructure>();
            this.tblPOQuotations = new HashSet<tblPOQuotation>();
            this.tblPOQuotations1 = new HashSet<tblPOQuotation>();
            this.tblPOQuotationSuppliers = new HashSet<tblPOQuotationSupplier>();
            this.tblPOQuotationSuppliers1 = new HashSet<tblPOQuotationSupplier>();
            this.tblPurchaseOrders = new HashSet<tblPurchaseOrder>();
            this.tblPurchaseOrders1 = new HashSet<tblPurchaseOrder>();
            this.tblPurchaseOrders2 = new HashSet<tblPurchaseOrder>();
            this.tblPurchaseOrders3 = new HashSet<tblPurchaseOrder>();
            this.tblPurchaseOrderInvoices = new HashSet<tblPurchaseOrderInvoice>();
            this.tblPurchaseOrderInvoices1 = new HashSet<tblPurchaseOrderInvoice>();
            this.tblPurchaseOrderInvoiceItemDetails = new HashSet<tblPurchaseOrderInvoiceItemDetail>();
            this.tblPurchaseOrderInvoiceItemDetails1 = new HashSet<tblPurchaseOrderInvoiceItemDetail>();
            this.tblPurchaseOrderWithItems = new HashSet<tblPurchaseOrderWithItem>();
            this.tblPurchaseOrderWithItems1 = new HashSet<tblPurchaseOrderWithItem>();
            this.tblPurchaseRequisitions = new HashSet<tblPurchaseRequisition>();
            this.tblPurchaseRequisitions1 = new HashSet<tblPurchaseRequisition>();
            this.tblPurchaseRequisitions2 = new HashSet<tblPurchaseRequisition>();
            this.tblPurchaseRequisitionItemsDetails = new HashSet<tblPurchaseRequisitionItemsDetail>();
            this.tblPurchaseRequisitionItemsDetails1 = new HashSet<tblPurchaseRequisitionItemsDetail>();
            this.tblRacks = new HashSet<tblRack>();
            this.tblRacks1 = new HashSet<tblRack>();
            this.tblReasons = new HashSet<tblReason>();
            this.tblReasons1 = new HashSet<tblReason>();
            this.tblReceiptDetails = new HashSet<tblReceiptDetail>();
            this.tblReceiptDetails1 = new HashSet<tblReceiptDetail>();
            this.tblReceiptWithBillDetails = new HashSet<tblReceiptWithBillDetail>();
            this.tblReceiptWithBillDetails1 = new HashSet<tblReceiptWithBillDetail>();
            this.tblSalesmanDetails = new HashSet<tblSalesmanDetail>();
            this.tblSalesmanDetails1 = new HashSet<tblSalesmanDetail>();
            this.tblSalesOrders = new HashSet<tblSalesOrder>();
            this.tblSalesOrders1 = new HashSet<tblSalesOrder>();
            this.tblSalesOrders2 = new HashSet<tblSalesOrder>();
            this.tblSalesOrders3 = new HashSet<tblSalesOrder>();
            this.tblSalesOrderCashTransactions = new HashSet<tblSalesOrderCashTransaction>();
            this.tblSalesOrderCashTransactions1 = new HashSet<tblSalesOrderCashTransaction>();
            this.tblSalesOrderInvoices = new HashSet<tblSalesOrderInvoice>();
            this.tblSalesOrderInvoices1 = new HashSet<tblSalesOrderInvoice>();
            this.tblSalesOrderInvoiceItemDetails = new HashSet<tblSalesOrderInvoiceItemDetail>();
            this.tblSalesOrderInvoiceItemDetails1 = new HashSet<tblSalesOrderInvoiceItemDetail>();
            this.tblSalesOrderItemWarehouseMaps = new HashSet<tblSalesOrderItemWarehouseMap>();
            this.tblSalesOrderItemWarehouseMaps1 = new HashSet<tblSalesOrderItemWarehouseMap>();
            this.tblSalesOrderWithItems = new HashSet<tblSalesOrderWithItem>();
            this.tblSalesOrderWithItems1 = new HashSet<tblSalesOrderWithItem>();
            this.tblStickerDetails = new HashSet<tblStickerDetail>();
            this.tblStickerDetails1 = new HashSet<tblStickerDetail>();
            this.tblStockTransferHeaders = new HashSet<tblStockTransferHeader>();
            this.tblStockTransferLineItems = new HashSet<tblStockTransferLineItem>();
            this.tblSubAccountGroupMasters = new HashSet<tblSubAccountGroupMaster>();
            this.tblSubAccountGroupMasters1 = new HashSet<tblSubAccountGroupMaster>();
            this.tblSubCategories = new HashSet<tblSubCategory>();
            this.tblSubCategories1 = new HashSet<tblSubCategory>();
            this.tblSubMenuRoleMaps = new HashSet<tblSubMenuRoleMap>();
            this.tblSubMenuRoleMaps1 = new HashSet<tblSubMenuRoleMap>();
            this.tblSysBranches = new HashSet<tblSysBranch>();
            this.tblSysBranches1 = new HashSet<tblSysBranch>();
            this.tblSysMainMenus = new HashSet<tblSysMainMenu>();
            this.tblSysMainMenus1 = new HashSet<tblSysMainMenu>();
            this.tblSysSubMenus = new HashSet<tblSysSubMenu>();
            this.tblSysSubMenus1 = new HashSet<tblSysSubMenu>();
            this.tblSysUser1 = new HashSet<tblSysUser>();
            this.tblTaxCESSes = new HashSet<tblTaxCESS>();
            this.tblUnitQuantities = new HashSet<tblUnitQuantity>();
            this.tblUOMs = new HashSet<tblUOM>();
            this.tblUserWarehouseMaps = new HashSet<tblUserWarehouseMap>();
            this.tblWarehouses = new HashSet<tblWarehouse>();
            this.tblWarehouseToWarehouseTrackings = new HashSet<tblWarehouseToWarehouseTracking>();
            this.tblSysUser11 = new HashSet<tblSysUser>();
            this.tblTaxCESSes1 = new HashSet<tblTaxCESS>();
            this.tblTransitItems = new HashSet<tblTransitItem>();
            this.tblTransitItemDetails = new HashSet<tblTransitItemDetail>();
            this.tblUnitQuantities1 = new HashSet<tblUnitQuantity>();
            this.tblUOMs1 = new HashSet<tblUOM>();
            this.tblUserWarehouseMaps1 = new HashSet<tblUserWarehouseMap>();
            this.tblWarehouses1 = new HashSet<tblWarehouse>();
            this.tblWarehouseToWarehouseTrackings1 = new HashSet<tblWarehouseToWarehouseTracking>();
            this.tblTransitItems1 = new HashSet<tblTransitItem>();
            this.tblTransitItemDetails1 = new HashSet<tblTransitItemDetail>();
            this.tblVoucherTypes = new HashSet<tblVoucherType>();
            this.tblVoucherTypes1 = new HashSet<tblVoucherType>();
            this.tblSysChannelPartners = new HashSet<tblSysChannelPartner>();
            this.tblSysChannelPartners1 = new HashSet<tblSysChannelPartner>();
        }
    
        public int UserID { get; set; }
        public string OrgID { get; set; }
        public string BranchID { get; set; }
        public string FName { get; set; }
        public string Alias { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> CanAddDiscount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string OldPassword { get; set; }
        public Nullable<int> NoofPassword { get; set; }
        public Nullable<System.DateTime> LoggedInDateTime { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDatetime { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
        public string DeviceId { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<bool> IsThresholdQtyAllowed { get; set; }
        public Nullable<bool> IsOTPVerified { get; set; }
        public string SMSOTP { get; set; }
        public string SystemAccess { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> State { get; set; }
        public string AdharNumber { get; set; }
        public string PanNumber { get; set; }
        public string Department { get; set; }
        public Nullable<int> ParentUserID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<bool> IsServiceInstalled { get; set; }
        public Nullable<bool> isFirstLogin { get; set; }
        public Nullable<bool> RememberPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscrepencyDetail> DiscrepencyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscrepencyDetail> DiscrepencyDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccessRight> tblAccessRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccessRight> tblAccessRights1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccessRight> tblAccessRights2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountGroup> tblAccountGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountGroupMaster> tblAccountGroupMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActivity> tblActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActivity> tblActivities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdminConfiguration> tblAdminConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdminConfiguration> tblAdminConfigurations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBatch> tblBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBatch> tblBatches1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBrand> tblBrands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBrand> tblBrands1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCart> tblCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategory> tblCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategory> tblCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerCreditDetail> tblCustomerCreditDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerVendorDetail> tblCustomerVendorDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerVendorDetail> tblCustomerVendorDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerVendorDetail> tblCustomerVendorDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDebtorsAreaDetail> tblDebtorsAreaDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDebtorsAreaDetail> tblDebtorsAreaDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDebtorsPlaceDetail> tblDebtorsPlaceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDebtorsPlaceDetail> tblDebtorsPlaceDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeliveryNote> tblDeliveryNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeliveryNote> tblDeliveryNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeliveryNoteItem> tblDeliveryNoteItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeliveryNoteItem> tblDeliveryNoteItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiscount> tblDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiscount> tblDiscounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGatePass> tblGatePasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGatePass> tblGatePasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGatePassItem> tblGatePassItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoodsInwardNote> tblGoodsInwardNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoodsInwardNote> tblGoodsInwardNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoodsInwardNoteItem> tblGoodsInwardNoteItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoodsInwardNoteItem> tblGoodsInwardNoteItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGRN> tblGRNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGRN> tblGRNs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGRNItem> tblGRNItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGRNItem> tblGRNItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHOBranchPriceDetail> tblHOBranchPriceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHOBranchPriceDetail> tblHOBranchPriceDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHOMasterPriceDetail> tblHOMasterPriceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHOMasterPriceDetail> tblHOMasterPriceDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHSNCode> tblHSNCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHSNCode> tblHSNCodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItem> tblItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItem> tblItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemCompany> tblItemCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemCompany> tblItemCompanies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemMappingWithCESS> tblItemMappingWithCESSes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemMappingWithCESS> tblItemMappingWithCESSes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemMovement> tblItemMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemParameterMap> tblItemParameterMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemParameterMap> tblItemParameterMaps1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemRate> tblItemRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemRate> tblItemRates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemStockTransferDestination> tblItemStockTransferDestinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemStockTransferHeader> tblItemStockTransferHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemStockTransferSource> tblItemStockTransferSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemSupplierMapping> tblItemSupplierMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemSupplierMapping> tblItemSupplierMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemToItemTracking> tblItemToItemTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemToItemTracking> tblItemToItemTrackings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemWarehouseMap> tblItemWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemWarehouseMap> tblItemWarehouseMaps1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotification> tblNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrganizationWarehouseMap> tblOrganizationWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrganizationWarehouseMap> tblOrganizationWarehouseMaps1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPacketSizeDetail> tblPacketSizeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPacketSizeDetail> tblPacketSizeDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParameter> tblParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParameter> tblParameters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaymentReceipt> tblPaymentReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaymentReceipt> tblPaymentReceipts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPercentageStructure> tblPercentageStructures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPercentageStructure> tblPercentageStructures1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOQuotation> tblPOQuotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOQuotation> tblPOQuotations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOQuotationSupplier> tblPOQuotationSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOQuotationSupplier> tblPOQuotationSuppliers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderInvoice> tblPurchaseOrderInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderInvoice> tblPurchaseOrderInvoices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderInvoiceItemDetail> tblPurchaseOrderInvoiceItemDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderInvoiceItemDetail> tblPurchaseOrderInvoiceItemDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderWithItem> tblPurchaseOrderWithItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderWithItem> tblPurchaseOrderWithItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseRequisition> tblPurchaseRequisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseRequisition> tblPurchaseRequisitions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseRequisition> tblPurchaseRequisitions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseRequisitionItemsDetail> tblPurchaseRequisitionItemsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseRequisitionItemsDetail> tblPurchaseRequisitionItemsDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRack> tblRacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRack> tblRacks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReason> tblReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReason> tblReasons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReceiptDetail> tblReceiptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReceiptDetail> tblReceiptDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReceiptWithBillDetail> tblReceiptWithBillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReceiptWithBillDetail> tblReceiptWithBillDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesmanDetail> tblSalesmanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesmanDetail> tblSalesmanDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrder> tblSalesOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrder> tblSalesOrders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrder> tblSalesOrders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrder> tblSalesOrders3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderCashTransaction> tblSalesOrderCashTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderCashTransaction> tblSalesOrderCashTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderInvoice> tblSalesOrderInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderInvoice> tblSalesOrderInvoices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderInvoiceItemDetail> tblSalesOrderInvoiceItemDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderInvoiceItemDetail> tblSalesOrderInvoiceItemDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderItemWarehouseMap> tblSalesOrderItemWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderItemWarehouseMap> tblSalesOrderItemWarehouseMaps1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderWithItem> tblSalesOrderWithItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderWithItem> tblSalesOrderWithItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStickerDetail> tblStickerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStickerDetail> tblStickerDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockTransferHeader> tblStockTransferHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockTransferLineItem> tblStockTransferLineItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubAccountGroupMaster> tblSubAccountGroupMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubAccountGroupMaster> tblSubAccountGroupMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubCategory> tblSubCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubCategory> tblSubCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubMenuRoleMap> tblSubMenuRoleMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubMenuRoleMap> tblSubMenuRoleMaps1 { get; set; }
        public virtual tblSysBranch tblSysBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysBranch> tblSysBranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysBranch> tblSysBranches1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysMainMenu> tblSysMainMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysMainMenu> tblSysMainMenus1 { get; set; }
        public virtual tblSysRole tblSysRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysSubMenu> tblSysSubMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysSubMenu> tblSysSubMenus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysUser> tblSysUser1 { get; set; }
        public virtual tblSysUser tblSysUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaxCESS> tblTaxCESSes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUnitQuantity> tblUnitQuantities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUOM> tblUOMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserWarehouseMap> tblUserWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWarehouse> tblWarehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWarehouseToWarehouseTracking> tblWarehouseToWarehouseTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysUser> tblSysUser11 { get; set; }
        public virtual tblSysUser tblSysUser3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaxCESS> tblTaxCESSes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransitItem> tblTransitItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransitItemDetail> tblTransitItemDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUnitQuantity> tblUnitQuantities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUOM> tblUOMs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserWarehouseMap> tblUserWarehouseMaps1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWarehouse> tblWarehouses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWarehouseToWarehouseTracking> tblWarehouseToWarehouseTrackings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransitItem> tblTransitItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransitItemDetail> tblTransitItemDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherType> tblVoucherTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherType> tblVoucherTypes1 { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
        public virtual tblSysOrganization tblSysOrganization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysChannelPartner> tblSysChannelPartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysChannelPartner> tblSysChannelPartners1 { get; set; }
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
