//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubMenuRoleMap
    {
        public int ID { get; set; }
        public int SubMenuID { get; set; }
        public int RoleID { get; set; }
        public int CreatedByID { get; set; }
        public int ActivityID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string OrgID { get; set; }
        public string SourceOfUpdate { get; set; }
        public string SystemAccess { get; set; }
        public Nullable<bool> IsEditable { get; set; }
    
        public virtual tblActivity tblActivity { get; set; }
        public virtual tblSysRole tblSysRole { get; set; }
        public virtual tblSysSubMenu tblSysSubMenu { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
    }
}
