//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStickerDetail
    {
        public int StickerId { get; set; }
        public string GRNNumber { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> WareHouseId { get; set; }
        public string SupplierName { get; set; }
        public System.DateTime DateOfReciept { get; set; }
        public Nullable<decimal> InwardQTY { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<int> NoOfStickersPrinted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string GINID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public string SourceOfUpdate { get; set; }
    
        public virtual tblGRN tblGRN { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
    }
}
