//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysOrganization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSysOrganization()
        {
            this.tblAccountLedgers = new HashSet<tblAccountLedger>();
            this.tblAccountReceiptDetails = new HashSet<tblAccountReceiptDetail>();
            this.tblAccountReceiptWithBillDetails = new HashSet<tblAccountReceiptWithBillDetail>();
            this.tblChannelPartnerMappings = new HashSet<tblChannelPartnerMapping>();
            this.tblCustomerVendorDetails = new HashSet<tblCustomerVendorDetail>();
            this.tblSysUsers = new HashSet<tblSysUser>();
        }
    
        public string OrgID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string GSTNumber { get; set; }
        public string ShippingAddress { get; set; }
        public string BillingAddress { get; set; }
        public string BillingLandmark { get; set; }
        public string ShippingLandmark { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string BusinessType { get; set; }
        public string CompanyType { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BankCode { get; set; }
        public string BankCity { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCNumber { get; set; }
        public string FSSAICode { get; set; }
        public Nullable<int> NoOfOutstandingBills { get; set; }
        public string CreditDays { get; set; }
        public Nullable<decimal> CreditLimitAmt { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PANNumber { get; set; }
        public string STNumber { get; set; }
        public string CSTNumber { get; set; }
        public string VATNumber { get; set; }
        public string MailingName { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string AlternateNumber { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingPinCode { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
        public string Declaration { get; set; }
        public string TermsAndConditions { get; set; }
        public Nullable<bool> IsServiceInstalled { get; set; }
        public Nullable<bool> IsTallyUsing { get; set; }
        public string SubscriptionKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountLedger> tblAccountLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountReceiptDetail> tblAccountReceiptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountReceiptWithBillDetail> tblAccountReceiptWithBillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChannelPartnerMapping> tblChannelPartnerMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerVendorDetail> tblCustomerVendorDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysUser> tblSysUsers { get; set; }
    }
}
