//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysChannelPartner
    {
        public string ChannelPartnerID { get; set; }
        public string ChannelPartnerName { get; set; }
        public string Description { get; set; }
        public string OrgID { get; set; }
        public string BranchID { get; set; }
        public string Phone { get; set; }
        public string ContactPerson { get; set; }
        public string Location { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string BillingLandmark { get; set; }
        public string ShippingLandmark { get; set; }
        public string BillingAddress { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string ShippingAddress { get; set; }
        public string MailingName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> FinancialYearStart { get; set; }
        public Nullable<System.DateTime> FinancialYearEnd { get; set; }
        public string BankName { get; set; }
        public string BankBranchName { get; set; }
        public string BankCity { get; set; }
        public string AlternateNumber { get; set; }
        public string ShippingPinCode { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string FSSAICode { get; set; }
        public string GST { get; set; }
        public string PANNumber { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public Nullable<bool> IsMappedToOrg { get; set; }
        public string MappedOrgID { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDatetime { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
        public Nullable<decimal> Quantitylimit { get; set; }
        public Nullable<int> ChannelTypeID { get; set; }
        public Nullable<int> AssociatedTo { get; set; }
        public Nullable<int> ParentChannelPartnerID { get; set; }
        public Nullable<int> BranchCity { get; set; }
        public Nullable<int> BranchState { get; set; }
    
        public virtual tblSysBranch tblSysBranch { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        public virtual tblSalesChannelType tblSalesChannelType { get; set; }
    }
}
