//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysOrganizationMap
    {
        public int ID { get; set; }
        public string ParentOrgID { get; set; }
        public string SisterOrgID { get; set; }
        public int Priority { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public string IsParent { get; set; }
        public Nullable<bool> IsMapped { get; set; }
        public Nullable<bool> IsDC { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
    }
}
