//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxLedger
    {
        public int ID { get; set; }
        public string OrgID { get; set; }
        public string Name { get; set; }
        public string Under { get; set; }
        public string TaxType { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool TallySync { get; set; }
        public bool IsTallyUpdated { get; set; }
    }
}
