//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucherType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVoucherType()
        {
            this.tblDeliveryNotes = new HashSet<tblDeliveryNote>();
            this.tblGatePasses = new HashSet<tblGatePass>();
            this.tblGoodsInwardNotes = new HashSet<tblGoodsInwardNote>();
            this.tblGRNs = new HashSet<tblGRN>();
            this.tblPurchaseOrders = new HashSet<tblPurchaseOrder>();
            this.tblPurchaseOrderInvoices = new HashSet<tblPurchaseOrderInvoice>();
            this.tblSalesOrders = new HashSet<tblSalesOrder>();
            this.tblSalesOrderInvoices = new HashSet<tblSalesOrderInvoice>();
            this.tblVoucherType1 = new HashSet<tblVoucherType>();
        }
    
        public string VoucherTypeNo { get; set; }
        public string Name { get; set; }
        public string Under { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string AllowNarration { get; set; }
        public string AliasOrAbbreviation { get; set; }
        public string DisplayColumn { get; set; }
        public string OrgID { get; set; }
        public string BranchID { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public Nullable<bool> IsTallyUpdated { get; set; }
        public Nullable<System.DateTime> TallyUpdatedDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeliveryNote> tblDeliveryNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGatePass> tblGatePasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoodsInwardNote> tblGoodsInwardNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGRN> tblGRNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderInvoice> tblPurchaseOrderInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrder> tblSalesOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderInvoice> tblSalesOrderInvoices { get; set; }
        public virtual tblSysBranch tblSysBranch { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherType> tblVoucherType1 { get; set; }
        public virtual tblVoucherType tblVoucherType2 { get; set; }
    }
}
