//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGRNItem
    {
        public int GRNItemsID { get; set; }
        public string GRNNumber { get; set; }
        public string ItemCode { get; set; }
        public int WareHouseId { get; set; }
        public decimal OrderedQuantity { get; set; }
        public decimal QuantityToBeInwarded { get; set; }
        public Nullable<decimal> DiscrepancyQty { get; set; }
        public Nullable<decimal> RejectedQty { get; set; }
        public decimal ReceivedQuantity { get; set; }
        public string ItemRemarks { get; set; }
        public bool IsTallyUpdated { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> WaveOff { get; set; }
        public string Status { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
    
        public virtual tblGRN tblGRN { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblReason tblReason { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
    }
}
