//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSMSTemplate
    {
        public int ID { get; set; }
        public string OrgID { get; set; }
        public string TemplateName { get; set; }
        public string TemplateBody { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
