//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesManAreaMappingChild
    {
        public int ID { get; set; }
        public Nullable<int> SalesManID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<bool> Value { get; set; }
        public Nullable<int> Pincode { get; set; }
    
        public virtual tblArea tblArea { get; set; }
        public virtual SalesManAreaMappingParent SalesManAreaMappingParent { get; set; }
    }
}
