//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemStockTransferDestination
    {
        public int ItemStockTransferDestinationID { get; set; }
        public Nullable<int> ItemStockTransferSourceID { get; set; }
        public string BT_Num { get; set; }
        public string ItemCode { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsTallyUpdated { get; set; }
        public Nullable<int> DestinationBatchID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string ShorgateAccountStatus { get; set; }
        public string Status { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblBatch tblBatch { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblItemStockTransferSource tblItemStockTransferSource { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
    }
}
