//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWarehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWarehouse()
        {
            this.DCQtyAllocationItemWarehouseMaps = new HashSet<DCQtyAllocationItemWarehouseMap>();
            this.DeliverycenterBranchMaps = new HashSet<DeliverycenterBranchMap>();
            this.DiscrepencyDetails = new HashSet<DiscrepencyDetail>();
            this.FumigationItemWrhsDetails = new HashSet<FumigationItemWrhsDetail>();
            this.tblDeliveryNoteItems = new HashSet<tblDeliveryNoteItem>();
            this.tblGatePassItems = new HashSet<tblGatePassItem>();
            this.tblGoodsInwardNoteItems = new HashSet<tblGoodsInwardNoteItem>();
            this.tblGRNItems = new HashSet<tblGRNItem>();
            this.tblItemMovements = new HashSet<tblItemMovement>();
            this.tblItemStockTransferDestinations = new HashSet<tblItemStockTransferDestination>();
            this.tblItemStockTransferSources = new HashSet<tblItemStockTransferSource>();
            this.tblItemSupplierMappings = new HashSet<tblItemSupplierMapping>();
            this.tblItemWarehouseMaps = new HashSet<tblItemWarehouseMap>();
            this.tblOrganizationWarehouseMaps = new HashSet<tblOrganizationWarehouseMap>();
            this.tblPurchaseOrders = new HashSet<tblPurchaseOrder>();
            this.tblPurchaseOrderInvoiceItemDetails = new HashSet<tblPurchaseOrderInvoiceItemDetail>();
            this.tblPurchaseOrderWithItems = new HashSet<tblPurchaseOrderWithItem>();
            this.tblPurchaseRequisitionItemsDetails = new HashSet<tblPurchaseRequisitionItemsDetail>();
            this.tblSalesOrderInvoiceItemDetails = new HashSet<tblSalesOrderInvoiceItemDetail>();
            this.tblSalesOrderItemWarehouseMaps = new HashSet<tblSalesOrderItemWarehouseMap>();
            this.tblStickerDetails = new HashSet<tblStickerDetail>();
            this.tblStockTransferLineItems = new HashSet<tblStockTransferLineItem>();
            this.tblStockTransferLineItems1 = new HashSet<tblStockTransferLineItem>();
            this.tblSysUsers = new HashSet<tblSysUser>();
            this.tblUserWarehouseMaps = new HashSet<tblUserWarehouseMap>();
        }
    
        public int WarehouseID { get; set; }
        public string IsWHorDC { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string LandMark { get; set; }
        public string City { get; set; }
        public string GPSLocation { get; set; }
        public string OrgID { get; set; }
        public string BranchID { get; set; }
        public string BillingLandmark { get; set; }
        public string ShippingLandmark { get; set; }
        public string ShippingPinCode { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string AlternateNumber { get; set; }
        public string BillingAddress { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string ShippingAddress { get; set; }
        public string MailingName { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
        public Nullable<bool> IsTallyUpdated { get; set; }
        public Nullable<System.DateTime> TallyUpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCQtyAllocationItemWarehouseMap> DCQtyAllocationItemWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliverycenterBranchMap> DeliverycenterBranchMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscrepencyDetail> DiscrepencyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FumigationItemWrhsDetail> FumigationItemWrhsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeliveryNoteItem> tblDeliveryNoteItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGatePassItem> tblGatePassItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoodsInwardNoteItem> tblGoodsInwardNoteItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGRNItem> tblGRNItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemMovement> tblItemMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemStockTransferDestination> tblItemStockTransferDestinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemStockTransferSource> tblItemStockTransferSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemSupplierMapping> tblItemSupplierMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemWarehouseMap> tblItemWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrganizationWarehouseMap> tblOrganizationWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderInvoiceItemDetail> tblPurchaseOrderInvoiceItemDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderWithItem> tblPurchaseOrderWithItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseRequisitionItemsDetail> tblPurchaseRequisitionItemsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderInvoiceItemDetail> tblSalesOrderInvoiceItemDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesOrderItemWarehouseMap> tblSalesOrderItemWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStickerDetail> tblStickerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockTransferLineItem> tblStockTransferLineItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockTransferLineItem> tblStockTransferLineItems1 { get; set; }
        public virtual tblSysBranch tblSysBranch { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSysUser> tblSysUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserWarehouseMap> tblUserWarehouseMaps { get; set; }
    }
}
