//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysUser()
        {
            this.tblSysOrganizations = new HashSet<SysOrganization>();
            this.tblSysOrganizations1 = new HashSet<SysOrganization>();
            this.tblSysUser1 = new HashSet<SysUser>();
            this.tblSysUser11 = new HashSet<SysUser>();
        }
    
        public int UserID { get; set; }
        public string OrgID { get; set; }
        public string BranchID { get; set; }
        public string FName { get; set; }
        public string Alias { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> CanAddDiscount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string OldPassword { get; set; }
        public Nullable<int> NoofPassword { get; set; }
        public Nullable<System.DateTime> LoggedInDateTime { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDatetime { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
        public string DeviceId { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysOrganization> tblSysOrganizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysOrganization> tblSysOrganizations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysUser> tblSysUser1 { get; set; }
        public virtual SysUser tblSysUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysUser> tblSysUser11 { get; set; }
        public virtual SysUser tblSysUser3 { get; set; }
    }
}
