//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseRequisitionItemsDetail
    {
        public int ItemDetailsReqNumber { get; set; }
        public string RequisitionNumber { get; set; }
        public string ItemCode { get; set; }
        public decimal Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsPoCreated { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
        public int WarehouseID { get; set; }
        public Nullable<int> DeliverycenterID { get; set; }
        public string Status { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblPurchaseRequisition tblPurchaseRequisition { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
    }
}
