//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentsSetting
    {
        public int ID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string OrgID { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<bool> IsGPRecord { get; set; }
        public Nullable<bool> IsGINRecord { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual DocumentsList DocumentsList { get; set; }
    }
}
