//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountContraBillWithDetail
    {
        public int ID { get; set; }
        public System.Guid ContraWithBillID { get; set; }
        public string ContraID { get; set; }
        public string CustID { get; set; }
        public string OutstandingAmt { get; set; }
        public string OrgID { get; set; }
        public string TransactionType { get; set; }
        public string BillType { get; set; }
        public string Billdatetime { get; set; }
        public Nullable<decimal> TallyAmount { get; set; }
        public Nullable<decimal> Discountamount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> Billamount { get; set; }
        public Nullable<bool> IsTallyUpdated { get; set; }
        public string SourceOfUpdate { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string IFSC { get; set; }
        public string AccountNumber { get; set; }
        public string TransactionNumber { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string BankOrCash { get; set; }
    
        public virtual tblAccountContraDetail tblAccountContraDetail { get; set; }
    }
}
