//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenominationMapWithTran
    {
        public System.Guid DenominationMapID { get; set; }
        public int DenominationID { get; set; }
        public string OrgID { get; set; }
        public Nullable<System.Guid> TransactionID { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<decimal> DenominationAmount { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
        public string PayOrRcpID { get; set; }
    
        public virtual CurrencyDenominationType CurrencyDenominationType { get; set; }
    }
}
