//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHOMasterPriceDetail
    {
        public int ID { get; set; }
        public int HOMasterPriceDetailsID { get; set; }
        public int CategoryID { get; set; }
        public string OrgID { get; set; }
        public string ItemCode { get; set; }
        public int RateID { get; set; }
        public Nullable<decimal> FreightCharges { get; set; }
        public Nullable<decimal> Loading_Unloading { get; set; }
        public Nullable<decimal> OtherExpenses { get; set; }
        public Nullable<decimal> LandingPrice { get; set; }
        public Nullable<int> BP1QtyLt { get; set; }
        public Nullable<int> BP1QtyGt { get; set; }
        public Nullable<decimal> Margin1 { get; set; }
        public Nullable<decimal> SellingPrice1 { get; set; }
        public Nullable<int> BP2QtyLt { get; set; }
        public Nullable<int> BP2QtyGt { get; set; }
        public Nullable<decimal> Margin2 { get; set; }
        public Nullable<decimal> SellingPrice2 { get; set; }
        public Nullable<int> BP3QtyLt { get; set; }
        public Nullable<int> BP3QtyGt { get; set; }
        public Nullable<decimal> Margin3 { get; set; }
        public Nullable<decimal> SellingPrice3 { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblItemRate tblItemRate { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
    }
}
