//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentReceipt
    {
        public int ID { get; set; }
        public string PaymentReceiptID { get; set; }
        public string IsRequestSent { get; set; }
        public string IsRequestReceived { get; set; }
        public string CustID { get; set; }
        public string CustName { get; set; }
        public string RequestSentDatetime { get; set; }
        public string RequestReceivedDatetime { get; set; }
        public string PaymentReceiptFromTally { get; set; }
        public string IsTallyUpdated { get; set; }
        public Nullable<int> SalesmanID { get; set; }
        public string SourceOfUpdate { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
    
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
    }
}
