//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblItemRate()
        {
            this.tblHOMasterPriceDetails = new HashSet<tblHOMasterPriceDetail>();
            this.tblItems = new HashSet<tblItem>();
            this.tblItemMappings = new HashSet<tblItemMapping>();
        }
    
        public int ID { get; set; }
        public int RateID { get; set; }
        public Nullable<decimal> BaseRateOther { get; set; }
        public Nullable<bool> IsOfferRate { get; set; }
        public Nullable<int> PerUnitRate { get; set; }
        public Nullable<int> ItemQTY1 { get; set; }
        public Nullable<int> ItemQTY2 { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<int> MRPPercentage { get; set; }
        public Nullable<decimal> DistributorPrice { get; set; }
        public Nullable<int> DistributorPercentage { get; set; }
        public Nullable<decimal> RetailerPrice { get; set; }
        public Nullable<int> RetailerPercentage { get; set; }
        public Nullable<decimal> SuperStockist { get; set; }
        public Nullable<int> SuperStockistPercentage { get; set; }
        public Nullable<decimal> DiscountFrom { get; set; }
        public Nullable<decimal> DiscountTo { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHOMasterPriceDetail> tblHOMasterPriceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItem> tblItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemMapping> tblItemMappings { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        public virtual tblUOM tblUOM { get; set; }
    }
}
