//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStateWithCity
    {
        public int ID { get; set; }
        public int StatewithCityID { get; set; }
        public int StateID { get; set; }
        public string VillageLocalityname { get; set; }
        public Nullable<int> DistrictID { get; set; }
    }
}
