//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FumigationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FumigationDetail()
        {
            this.FumigationItemWrhsDetails = new HashSet<FumigationItemWrhsDetail>();
        }
    
        public int FuminID { get; set; }
        public string FuminVchrNum { get; set; }
        public Nullable<System.DateTime> FuminDate { get; set; }
        public Nullable<System.DateTime> FuminStartDate { get; set; }
        public Nullable<System.DateTime> FuminEndDate { get; set; }
        public string FuminStatus { get; set; }
        public Nullable<int> FuminPartyOrSupp { get; set; }
        public string FuminPartyOrSuppID { get; set; }
        public string FuminPartyInHouseName { get; set; }
        public string FuminCustomer { get; set; }
        public string FuminInhouseCust { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public byte[] ImageCertificate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FumigationItemWrhsDetail> FumigationItemWrhsDetails { get; set; }
    }
}
