//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProcessitem_Master
    {
        public int ID { get; set; }
        public string ItemCode { get; set; }
        public string TallyItemName { get; set; }
        public string ItemName { get; set; }
        public string Alias { get; set; }
        public string OrgID { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<int> BaseUnit { get; set; }
        public Nullable<decimal> BasePKTValue { get; set; }
        public Nullable<int> AlternateUnit { get; set; }
        public Nullable<decimal> AlternatePKTValue { get; set; }
        public Nullable<int> PacketUOMID { get; set; }
        public Nullable<decimal> PacketQTY { get; set; }
        public Nullable<int> BagUOMID { get; set; }
        public Nullable<decimal> BagQTY { get; set; }
        public Nullable<bool> IsTallyUpdated { get; set; }
        public Nullable<bool> IsParentTallyUpdated { get; set; }
        public Nullable<bool> IsCESSMapped { get; set; }
        public Nullable<decimal> CESSValue { get; set; }
        public Nullable<System.DateTime> CESSEffectiveDate { get; set; }
        public int BrandID { get; set; }
        public int CategoryID { get; set; }
        public int SubCategoryID { get; set; }
        public Nullable<int> RackID { get; set; }
        public string ItemDetail { get; set; }
        public string StorageArea { get; set; }
        public Nullable<bool> AllowNegativeStock { get; set; }
        public Nullable<bool> IsItemBlocked { get; set; }
        public decimal GST { get; set; }
        public Nullable<System.DateTime> GSTEffectiveDate { get; set; }
        public string IGST { get; set; }
        public string CGST { get; set; }
        public string SGST { get; set; }
        public Nullable<int> ReOrderlevel { get; set; }
        public Nullable<int> ReOrderQTY { get; set; }
        public Nullable<bool> IsReturnable { get; set; }
        public Nullable<bool> IsTrademarkRegistered { get; set; }
        public string PreDefinedBarCode { get; set; }
        public string SourceOfUpdate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DaysToRefill { get; set; }
        public Nullable<int> HSNCode { get; set; }
        public Nullable<int> HSNSubCode { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> finisheditem_sale { get; set; }
    }
}
