//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicExpensesDetail
    {
        public int BaiscExpID { get; set; }
        public int ExpsID { get; set; }
        public string OrgID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubcategoryID { get; set; }
        public string BranchID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> ValueInPer { get; set; }
        public bool IsValueInPercentage { get; set; }
        public string Unit { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblSysBranch tblSysBranch { get; set; }
        public virtual TypeOfExpens TypeOfExpens { get; set; }
    }
}
