//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountCreditNoteWithBillDetail
    {
        public int ID { get; set; }
        public System.Guid CreditNoteWithBillID { get; set; }
        public string CreditNoteID { get; set; }
        public string LedgerID { get; set; }
        public string CustID { get; set; }
        public string OutstandingAmt { get; set; }
        public string OrgID { get; set; }
        public string BillType { get; set; }
        public string BillNo { get; set; }
        public string Billdatetime { get; set; }
        public Nullable<decimal> TallyAmount { get; set; }
        public Nullable<decimal> Discountamount { get; set; }
        public Nullable<decimal> Billamount { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<bool> IsTallyUpdated { get; set; }
        public string SourceOfUpdate { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ToLedgerID { get; set; }
    
        public virtual tblAccountCreditNoteDetail tblAccountCreditNoteDetail { get; set; }
        public virtual tblAccountCreditNoteWithBillDetail tblAccountCreditNoteWithBillDetails1 { get; set; }
        public virtual tblAccountCreditNoteWithBillDetail tblAccountCreditNoteWithBillDetail1 { get; set; }
    }
}
