//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArea()
        {
            this.SalesManAreaMappingChilds = new HashSet<SalesManAreaMappingChild>();
        }
    
        public Nullable<int> ID { get; set; }
        public Nullable<int> CityID { get; set; }
        public int AreaID { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> Pincode { get; set; }
        public Nullable<bool> Value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesManAreaMappingChild> SalesManAreaMappingChilds { get; set; }
        public virtual tblCity tblCity { get; set; }
    }
}
