//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemWarehouseMap
    {
        public int ItemWarehouseMapID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<bool> IsOBStockUpdatedToTally { get; set; }
        public string GRNNumber { get; set; }
        public int WarehouseID { get; set; }
        public string OrgID { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> SaleQuantity { get; set; }
        public Nullable<decimal> InfectedQty { get; set; }
        public Nullable<decimal> DeliveredQTY { get; set; }
        public Nullable<int> BatchID { get; set; }
        public string BranchID { get; set; }
        public bool IsActive { get; set; }
        public string SourceOfUpdate { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string GINID { get; set; }
        public string Status { get; set; }
    
        public virtual tblGRN tblGRN { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblSysBranch tblSysBranch { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
    }
}
