//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGroupDetail
    {
        public int ID { get; set; }
        public string OrgID { get; set; }
        public string BranchID { get; set; }
        public string AccGroupName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentGroupID { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> isTallyUpdated { get; set; }
        public Nullable<System.DateTime> TallyUpdatedDate { get; set; }
        public Nullable<int> TallyUpdatedByID { get; set; }
    }
}
