//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemThresholdQtyDetail
    {
        public int Id { get; set; }
        public string OrgId { get; set; }
        public string BranchID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> BusinessTypeID { get; set; }
        public Nullable<int> MaxQty { get; set; }
        public Nullable<int> MinQty { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual BusinessType BusinessType { get; set; }
        public virtual tblItem tblItem { get; set; }
    }
}
