//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPCN_Details
    {
        public int pcndeatils_idpk { get; set; }
        public string pcn_num { get; set; }
        public string Voucher_IDFK { get; set; }
        public string itemcode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Quantity_Qtl { get; set; }
        public Nullable<int> Process_Id { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string Status { get; set; }
        public string Batch_Number { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Pitemcode { get; set; }
        public Nullable<decimal> PQuantity { get; set; }
        public Nullable<decimal> PRate { get; set; }
        public Nullable<decimal> PAmount { get; set; }
        public Nullable<bool> IsTallyUpdated { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Updated_by { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual tblPNCN tblPNCN { get; set; }
    }
}
