//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrderWithItem
    {
        public int ID { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> PacketSizeID { get; set; }
        public Nullable<int> BagSizeID { get; set; }
        public string BagQTY { get; set; }
        public Nullable<decimal> TotalQTY { get; set; }
        public Nullable<decimal> BilledQty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> TaxValue { get; set; }
        public Nullable<decimal> BaseValue { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public string Remarks { get; set; }
        public bool IsTallyUpdated { get; set; }
        public Nullable<int> ItemRowNumber { get; set; }
        public int WarehouseID { get; set; }
        public string Status { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblPurchaseOrder tblPurchaseOrder { get; set; }
        public virtual tblReason tblReason { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        public virtual tblWarehouse tblWarehouse { get; set; }
    }
}
