//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPurchaseRequisition()
        {
            this.DCQtyAllocationItemWarehouseMaps = new HashSet<DCQtyAllocationItemWarehouseMap>();
            this.tblPurchaseOrders = new HashSet<tblPurchaseOrder>();
            this.tblPurchaseRequisitionItemsDetails = new HashSet<tblPurchaseRequisitionItemsDetail>();
        }
    
        public int ID { get; set; }
        public string RequisitionNumber { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public string RequisitionRequester { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public string RequestedName { get; set; }
        public string ContactNumber { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public string SourceOfUpdate { get; set; }
        public string BranchID { get; set; }
        public string OrgID { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCQtyAllocationItemWarehouseMap> DCQtyAllocationItemWarehouseMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseRequisitionItemsDetail> tblPurchaseRequisitionItemsDetails { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblSysBranch tblSysBranch { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
        public virtual tblSysUser tblSysUser2 { get; set; }
    }
}
